services:
  proxy_redis:
    image: "redis"
    # ports:
    #   - "6379:6379"

  proxy_pool:
    build: .
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
